### ISSUE TITLE
Article "Simple Jar Libs" for update

### ISSUE THREAD

**Issue by NickIliev** [NativeScript/android-runtime-docs#15]
The following articles:
[https://docs.nativescript.org/runtimes/android/external-libs/jars](https://docs.nativescript.org/runtimes/android/external-libs/jars)
[https://docs.nativescript.org/runtimes/android/external-libs/resource-libs](https://docs.nativescript.org/runtimes/android/external-libs/resource-libs)
are still reffering **tns library add android** as a supported command.
The both need to be updated as **tns library** is no longer supported.

**Comment by Pip3r4o** [comment]
Noted, will take a look at those. Thanks!

**Comment by Pip3r4o** [comment]
It would appear that we've forgotten to drop the **tns library** articles when the respective commands were removed. The way to add and use platform-specific libraries now is through npm packages whose android/ios implementations reside in platforms -> android/ios folders.

**Comment by Pip3r4o** [comment]
The articles have been removed altogether
